firm:
	@rm -f firmware/neobee_wemos_latest-debug.bin
	@rm -f firmware/neobee_wemos_latest.bin
	@cp .pio/build/wemos_debug/firmware.bin firmware/neobee_wemos_latest-debug.bin
	@cp .pio/build/wemos_release/firmware.bin firmware/neobee_wemos_latest.bin
